apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-vendas-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-vendas
  template:
    metadata:
      labels:
        app: api-vendas
    spec:
      containers:
      - name: api-vendas
        image: gabrielainfnet/api-vendas:1.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /api-vendas/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api-vendas/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
      restartPolicy: Always