global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/api-vendas/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['api-vendas-service:8080']
        labels:
          alias: api-vendas-service